[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.12.2"
  NPM_VERSION = "10.5.0"
  YARN_VERSION = "1.22.22"

[[plugins]]
  package = "@netlify/plugin-gatsby"
