[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  YARN_VERSION = "1.22.22"

[[plugins]]
  package = "@netlify/plugin-gatsby"
